### PR TITLE
Add docs for Terraform

### PR DESCRIPTION
**Pull request by AndrewGuenther**

### CODE REVIEW

**Comment by AndrewGuenther** [comment]
@RaJiska would like to get your input on this. I pulled the "vanilla" HCL from some comments others had added to the issue, but would appreciate if you could confirm if it is valid for me.

**Comment by AndrewGuenther** [comment]
I cannot for the life of me get syntax highlighting to work on the HCL :disappointed:

**Comment by RaJiska** [comment]
Looks great! Thank you for adding Terraform in the documentation.

The syntax it looks all good ye. You can use `terraform validate` to for linting the code, you'd have to replace implied references with strings for this to work.

As for syntax highlighting, I use VSCode, the main extension is pretty lame and does not work (well). I use [this extensions](https://marketplace.visualstudio.com/items?itemName=4ops.terraform) which offers quite decent results.

**Comment by AndrewGuenther** [comment]
I meant that the syntax highlighting in the generated docs doesn't seem to be working even though mkdocs-material/pygments claim it is supported. Not going to block on it though. Some docs is better than pretty docs.

**Comment by RaJiska** [comment]
Unfortunately I'm not familiar with the tool.

Something else that does not seem to work though are tables: https://fck-nat.dev/develop/configuration/ ; it seems to work in Github, but all messed up on the website.

**Pull request merged**
