### PR TITLE
Remove EIP requirement for HA mode

### PR DESCRIPTION
**Pull request by AndrewGuenther**
Based on the conversation in !12, but I can't push to @JulianCBC's branch.

### CODE REVIEW

**Review by JulianCBC — APPROVED** [review]
Looks good to me, that's a clever trick, I didn't know you could get that sort of data from the metatdata host.

**Comment by AndrewGuenther** [comment]
Was waffling on whether or not to make any of these values configurable, but I don't think it is needed for now.

**Comment by JulianCBC** [comment]
Something that came up here: https://github.com/int128/terraform-aws-nat-instance/issues/35#issuecomment-1196148170 is that there are situations where the source IP of the NATted traffic needs to be constant or at least known in advance, so this should be configurable.

**Comment by AndrewGuenther** [comment]
The EIP can still get attached to eth0, this doesn't prevent that from happening. I think this is more of an issue with how they do EIP attachment than a fundamental limitation.

**Comment by JulianCBC** [comment]
Makes sense!

**Pull request merged**
